### ISSUE TITLE
Different results with same population set

### ISSUE THREAD

**Issue by Selldor** [agouy/straf#6] opened 2022-10-05 12:43 UTC
**Describe the bug**
I found that empty lines in the input file are counted towards the N and the Nall column of the tables in Forensic and Population genetics tables.
Empty lines seem to have influence on allele frequency an i got Fst and Fis Values while the empty line was Included in a file with the one population. 
The above happened while using the online version here : https://straf-p7bdrhm3xq-ew.a.run.app/ on the 5th October in 2022

Trying the "local" version generated HWE and LD values of 1.0 fo all loci and loci pairs, so i immediately switched to the online version.

EDIT 07.10.2022:

Also:
This might be more of a question than a bug.
I used the same population of 950 individuals in two different analysis, once as one population and once divided into 5 populations and i got different results for the HWE. The main Difference being that in the file with the separate populations only one marker hat a p-value below 0.05 in the "all" tab whereas several marker in the sub populations had p-values < 0.05. Running the same samples as one population all the markers with p-values < 0.05 in the sub populations showed a comparable low p-value < 0.05 in the whole population.

A colleague (mathematician) looked at Fisher's exact test with Monte Carlo simulations described in Guo 1992 that you cited for STRAF, to help with the above problem: how to structure my population to get the correct result for HWE. 
She said that with the 1000 permutations it should be expected that the results differ between runs, since the randomly picked genotypes should differ between runs. So i reran the sample sets and got the exact same results for the p-values for the same sample set. How can that be ?

**To Reproduce**
Tried it multiple times.  
I will check if I am allowed to send you the files to try it yourself.

**Screenshots**

**Comment by agouy** [comment] 2022-10-10 08:34
Thanks for reporting this bug; I'll investigate and try to reproduce the issue on my end in the next weeks.

Regarding your questions:
* there seems to be a difference between the global ("all") p-value when sub-populations are defined comparing to when they are defined as a single population. This is likely due to the fact that Genepop, used to perform HW test in STRAF, has a specific procedure to compute global p-values when multiple populations are present. It does not compute the p-value of the merged population but rather aggregate p-values using [Fisher's method to combine tests](https://en.wikipedia.org/wiki/Fisher%27s_method). I will document this behaviour in the STRAF book, thank you for capturing this.

* I would have expected different results with only 1000 iterations as well. However, since version 2.0, STRAF uses Genepop to perform HW test. Having a closer look at the genepop documentation, permutations are run in batches (in our case, 100 batches) of 1000 iterations each, so 100k iterations in total. Then it keeps the best run in terms of likelihood. So it's not surprising that the results converge with not so many permutations.

**Comment by Selldor** [comment] 2022-10-14 07:13
Thank you.
That makes things clearer and solved my issues with interpretation.

Best

Christian

Alexandre Gouy ***@***.***> schrieb am Mo., 10. Okt. 2022,
10:34:

**Comment by agouy** [comment] 2022-10-21 07:24
This is fixed in version 2.1.4, note that the issue affected only diploid datasets and did not affect individual populations or other metrics.  This version also increases the time before the session ends because of inactivity (app was grayed out quite early).

Thanks again for reporting this! Closing the issue.

**Closed by agouy** 2022-10-21 07:24 UTC
Labels: bug
